apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: malware-scanner-service
spec:
  template:
    spec:
      containers:
      - name: malware-scanner-api
        image: localhost:32000/malware-scanner-service:latest