name: $(Build.BuildId)
pool:
  vmImage: 'ubuntu-16.04'
trigger:
- master
steps:

- bash: |
   sudo pip install setuptools
   sudo pip install awscli
   export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
   chmod +x ./pipeline.sh
   ./pipeline.sh $(Build.BuildId) $(System.DefaultWorkingDirectory)
  displayName: Pipeline Bash Script

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: manifests"
  inputs:
    PathtoPublish: deployment/k8s
    ArtifactName: manifests

- bash: |
   chmod +x ./deployment/k8s/set-image.sh
   chmod +x ./deployment/k8s/update-git.sh
   chmod +x ./deployment/k8s/set-production-image-tag.sh

   ./deployment/k8s/set-production-image-tag.sh --tag $(Build.BuildId)
  displayName: Set production image tag