apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: malware-scanner-service
  namespace: malware-scan
  labels:
    department: logistics
    app: malware-scanner-service
    component: api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: malware-scanner-service
  template:
    metadata:
      labels:
        app: malware-scanner-service
        project: selfservice
        department: logistics
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: malware-scanner-api
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/malware-scan/malware-scanner-service:147430
        ports:
        - containerPort: 8081
          name: main
        volumeMounts:
        - name: shared-data
          mountPath: /app/data/
      - name: malware-scanner
        image: rordi/docker-antivirus
        volumeMounts:
        - name: shared-data
          mountPath: /data/av/