apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: malware-scanner-service
  namespace: malware-scan
  labels:
    department: logistics
    app: malware-scanner-service
    component: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malware-scanner-service
  template:
    metadata:
      labels:
        app: malware-scanner-service
        project: selfservice
        department: logistics
    spec:
      containers:
      - name: malware-scanner-service
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/malware-scan/malware-scanner-service:146139
        ports:
        - containerPort: 8081
          name: main