apiVersion: v1
kind: Service
metadata:
  name: malware-scanner-service
  namespace: malware-scan
  labels:
    department: logistics
    app: malware-scanner-service
    component: api-service
spec:
  ports:
  - name: main
    port: 80
    targetPort: main
  selector:
    app: malware-scanner-service
