version: '2'

services:

  docker-av:
    image: rordi/docker-antivirus
    container_name: docker-av
    volumes:
      - ./../src/api-server/data/queue:/data/av/queue
      - ./../src/api-server/data/ok:/data/av/ok
      - ./../src/api-server/data/nok:/data/av/nok
      - ./logs:/var/log/supervisor/
    networks:
      - avnetwork

networks:
  avnetwork:
